services:
  hwdatabase:
    image: postgres:16-bookworm
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxihw
    volumes:
      - "./data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=root
#    ports:
#      - "8080:80"
